### ISSUE TITLE
upload_appveyor_builds.py does not work with twine >= 1.6.0

### ISSUE THREAD

**Issue by dahlia** [dahlia/libsass-python#97]
```
Downloading dist/libsass-0.9.1-cp27-none-win32.whl...
Downloading dist/libsass-0.9.1-cp27-none-win_amd64.whl...
Downloading dist/libsass-0.9.1-cp33-none-win32.whl...
Downloading dist/libsass-0.9.1-cp33-none-win_amd64.whl...
Downloading dist/libsass-0.9.1-cp34-none-win32.whl...
Downloading dist/libsass-0.9.1-cp34-none-win_amd64.whl...
Uploading 6 file(s)...
Traceback (most recent call last):
  File "./upload_appveyor_builds.py", line 140, in <module>
    main()
  File "./upload_appveyor_builds.py", line 135, in main
    dists=dists
TypeError: upload() missing 2 required positional arguments: 'config_file' and 'skip_existing'
```

Twine seems change their internal API since 1.6.0.

**Comment by asottile** [comment]
I've got this :)

**Comment by dahlia** [comment]
:+1:
